//
// Created by 35802 on 2022/8/4.
//

#ifndef UARTTEST_MOVEMENTSTABLE_H
#define UARTTEST_MOVEMENTSTABLE_H
#define MOVE_STRAIGHT_SLICE_NUM 30
#define LEGS_NUM 6
#define SERVO_PER_LEG 3

#endif //UARTTEST_MOVEMENTSTABLE_H
